docker-up
    sudo docker-compose up -d

docker-down
    sudo docker-compose down

docker-build
    sudo docker-compose up --build -d

test:
    sudo docker exec shopping-php-cli vendor/bin/phpunit --colors=always

perm:
    sudo chown $(USER):$(USER) bootstrap/cache -R